XML to JSON now reads a base64 string and returns a JSON dict
sesam-community/xml pull request #6
Opened 2021-08-09 12:26 UTC by kruand-sesam

instead of reading XML string input. Updated Dockerfile - removed deprecated MAINTAINER, added LABEL instead

2021-08-09 13:52 UTC, JonasAls89 requested changes

2021-08-09 13:52 UTC, JonasAls89 commented on Dockerfile
> +LABEL author.email="jonas.christensen@sesam.io"
du vil ikke stå som author? eller Endre? Tror aldrig jeg har skrevet på denne.. :)

2021-08-09 14:06 UTC, kruand-sesam commented on Dockerfile
> +LABEL author.email="jonas.christensen@sesam.io"
Jo, null problem.
Da setter jeg den til Endre.

2021-08-10 09:10 UTC, JonasAls89 approved these changes

2021-08-10 09:12 UTC, merged